version: '3.8'

services:
  avito-pvz-service:
      build: .
      container_name: avito-pvz-service
      ports:
        - "8080:8080"
      env_file:
        - .env
      depends_on:
        db:
            condition: service_healthy
      networks:
        - internal
  
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${avito_pvz}
    volumes:
      # "./migrations/init.sql" - путь к миграциям БД
      - ./migrations/000001_init.up.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d avito_pvz'"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal
networks:
  internal: